### ISSUE TITLE
ssh connection with wrong IP

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-gorgone#65] opened 2020-10-09 20:24 UTC
Centreon Gorgone 20.04.5
CentOS 7.8

IP changed on Poller configuration, gorgone is using wrong IP
![image](https://user-images.githubusercontent.com/6400595/95628322-1508fe00-0a7e-11eb-89c1-cda1521181f7.png)
After restarting gorgone service problem solved

**Comment by cgagnaire** [comment] 2020-10-12 15:21
Hi @joschi99,
That's an odd one!
Are you using _register_ module with some config to overload Poller's config?

**Comment by joschi99** [comment] 2020-10-12 15:29
not sure what you mean with register module. Poller configuration was duplicated from another Poller configuration, but everything was done manually. There is no overload or something particularly. But since we restart gorgone it's working correctly.
But as you can see on the screenshot the log is using another/wrong ip address. How can I help you?

**Comment by cgagnaire** [comment] 2020-10-12 15:36
Is that the IP coming from the source of the duplication ?
If so, the "problem" may come from the fact that Gorgone refreshes its target every 10 minutes or so. So if you changed the IP between to refresh you may have this problem.

**Comment by joschi99** [comment] 2020-10-12 15:46
Maybe. I have done a quick test in lab and if I change IP address on Poller configuration the gorgone process will still use the old one, if I do Poller Export. On the audit logs I can see that the Poller was changed from 95.171.41.17 to 95.171.41.20 on 3.37pm, but if you look the timestamp on the logfile at 9.11pm Gorgone has still used old address:

![image](https://user-images.githubusercontent.com/6400595/95765699-87faba80-0cb2-11eb-8273-ba47ef431a11.png)

Is there maybe some problem with target list refresh?

**Comment by cgagnaire** [comment] 2020-10-12 15:48
I'll let @garnier-quentin answer here.

**Comment by garnier-quentin** [comment] 2020-10-13 07:15
Could you provide the gorgone log file (central server) in debug mode please ?

**Comment by garnier-quentin** [comment] 2020-10-16 14:36
Do you have some news @joschi99 ?

**Comment by joschi99** [comment] 2020-10-19 07:25
Hi @garnier-quentin.
i could enable debug mode and send you the logs, but after gorgone restart we are not able to reproduce the problem anymore. Let me know if you would like to have still the debug logs.

**Comment by garnier-quentin** [comment] 2020-10-19 07:45
Yes. You can enable the debug (restart gorgone) and change poller configuration. If you have the problem, you can send me the log.

**Comment by joschi99** [comment] 2020-10-21 14:37
I'm not able to reproduce the problem. If I change the IP from a Poller after some minutes gorgone seem's updated and working. I have no idea how rebuild this problem, but if you look timestamp on images between logs (21pm) and Poller config change from audit log (3PM) problem was there.
Any idea?

**Comment by garnier-quentin** [comment] 2020-10-21 14:39
Don't have an idea. We close it. If someone have that issue, we need the logs to resolve it (if the issue is still here)

**Closed by garnier-quentin** 2020-10-21 14:39 UTC
